version: "latest"

services:
  backend:
    build: .
    ports: 
      - "80:80"
    links:
      - database

  database:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kevin123
      MYSQL_DATABASE: academysibd
      # MYSQL_USER: root
      # MYSQL_PASSWORD: kevin123