from .Administrador import administrador
from .Asignatura import asignatura
from .Asistencia import asistencias
from .Año_academico import año_academico
from .Calificacion import calificaciones
from .Docente import docente
from .Estudiante import estudiante
from .Gestion_asignatura import gestion_asignatura
from .Grado_escolar import grado_escolar
from .Grupo import grupo
from .Horario import horario
from .Periodo import periodo
from .Usuario import usuario