"""Inicial

Revision ID: 87e75e08269a
Revises: 
Create Date: 2024-04-22 16:52:52.016122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e75e08269a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_administrador',
    sa.Column('id_administrador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_administrador')
    )
    op.create_table('tb_asignaturas',
    sa.Column('id_asignatura', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_asignatura')
    )
    op.create_table('tb_asistencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_año_academico',
    sa.Column('id_añoAcademico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_añoAcademico')
    )
    op.create_table('tb_calificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_docentes',
    sa.Column('id_docente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('apellidos', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_docente')
    )
    op.create_table('tb_estudiantes',
    sa.Column('id_estudiantes', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_estudiantes')
    )
    op.create_table('tb_grado_escolar',
    sa.Column('id_gradoEscolar', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_gradoEscolar')
    )
    op.create_table('tb_grupos',
    sa.Column('id_grupo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('tb_horarios',
    sa.Column('id_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('tb_periodos',
    sa.Column('id_periodo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_periodo')
    )
    op.create_table('tb_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('permisos', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asociacion_año_grado',
    sa.Column('año_academico_id', sa.Integer(), nullable=False),
    sa.Column('grado_escolar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['año_academico_id'], ['tb_año_academico.id_añoAcademico'], ),
    sa.ForeignKeyConstraint(['grado_escolar_id'], ['tb_grado_escolar.id_gradoEscolar'], ),
    sa.PrimaryKeyConstraint('año_academico_id', 'grado_escolar_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asociacion_año_grado')
    op.drop_table('tb_usuarios')
    op.drop_table('tb_periodos')
    op.drop_table('tb_horarios')
    op.drop_table('tb_grupos')
    op.drop_table('tb_grado_escolar')
    op.drop_table('tb_estudiantes')
    op.drop_table('tb_docentes')
    op.drop_table('tb_calificaciones')
    op.drop_table('tb_año_academico')
    op.drop_table('tb_asistencias')
    op.drop_table('tb_asignaturas')
    op.drop_table('tb_administrador')
    # ### end Alembic commands ###
